<div class="content-header">
    <h1 class="header-title">Laporan Transaksi</h1>
</div>
<div class="content-body">
    <!-- Tabs -->
    <ul class="nav custom-tabs mb-4">
        <li class="nav-item">
            <a href="javascript:void(0);" id="tabItProvider" class="nav-link pt-1 active c-16"
                data-url="/reports/index">
                Mitra Acquirer
            </a>
        </li>
        <li class="nav-item">
            <a href="javascript:void(0);" id="tabMitra" class="nav-link pt-1 c-16" data-url="/reports/index/mitra">
                Sub Mitra Acquirer
            </a>
        </li>
    </ul>

    <div class="card card-accordion shadow-none mb-4" id="reportTransactionMitra">
        <div class="card-header" data-bs-toggle="collapse" data-bs-target="#collapseReportMitra" aria-expanded="true"
            aria-controls="collapseReportMitra">
            <div class="card-title">
                <div class="d-flex flex-column">
                    <h1 class="fs-6 font-bold mb-0">List Data</h1>
                </div>
            </div>
        </div>
        <div id="collapseReportMitra" class="accordion-collapse collapse show" data-bs-parent="#reportTransactionMitra">
            <div class="accordion-body">
                <!-- Summary -->
                <div class="row g-0 border rounded-4 mb-4 mx-4">
                    <div class="col-lg-3">
                        <div class="summary-item">
                            <div class="summary-icon">
                                <i class="bi bi-file-earmark-text"></i>
                            </div>
                            <div class="d-flex flex-column flex-fill gap-1">
                                <div class="summary-title text-neutral-100">Total Lembar</div>
                                <div class="summary-value c-16" id="lblLembar"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="summary-item">
                            <div class="summary-icon-tagihan"></div>
                            <div class="d-flex flex-column flex-fill gap-1">
                                <div class="summary-title text-neutral-100">Total Tagihan</div>
                                <div class="summary-value c-16" id="lblTagihan"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="summary-item">
                            <div class="summary-icon-admin"></div>
                            <div class="d-flex flex-column flex-fill gap-1">
                                <div class="summary-title text-neutral-100">Total Admin Mitra Acquirer</div>
                                <div class="summary-value c-16" id="lblAdmin"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="summary-item">
                            <div class="summary-icon-nominal"></div>
                            <div class="d-flex flex-column flex-fill gap-1">
                                <div class="summary-title text-neutral-100">Total Nominal</div>
                                <div class="summary-value c-16" id="lblTotal"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Filter -->
                <div class="d-flex flex-column gap-4 px-4 mb-4">
                    <div class="d-flex gap-3">
                        <div class="form-group">
                            <select name="lengthData" id="lengthData" class="form-select">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                            </select>
                        </div>
                        <div class="form-group flex-fill">
                            <div class="position-relative">
                                <div class="search-icon">
                                    <span class="icon-search-append"></span>
                                </div>
                                <input id="keyword" type="text" class="form-control ps-5" placeholder="Cari"
                                    autocomplete="off" />
                            </div>
                        </div>
                        <div class="form-group w-20">
                            <select name="listitp" id="listitp" class="form-select select2" data-allow-clear="false"
                                data-placeholder="Pilih Mitra Acquirer">
                                <option value=""></option>
                                <?php foreach ($this->listData as $key => $value) : ?>
                                <option value="<?php echo $value['technical_provider_code']; ?>">
                                    <?php echo $value['nama_technical_provider']; ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group flex-fit">
                            <div class="input-append append-right">
                                <input id="filterDateMitra" type="text" name="date" class="form-control"
                                    placeholder="Masukkan tanggal" data-toggle="datepicker" data-auto-apply="true" />
                                <div class="append-icon icon-calendar"></div>
                            </div>
                        </div>
                        <div class="form-group flex-fit">
                            <select name="layanan" id="layanan" class="form-select select2" data-allow-clear="false"
                                data-placeholder="Pilih Layanan">
                                <option value=""></option>
                                <?php foreach ($this->layanan as $key => $value) : ?>
                                <option value="<?php echo $key; ?>"
                                    <?php echo ($this->selectedLayanan == $value) ? 'selected="selected"' : ''; ?>>
                                    <?php echo $value; ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-outline-primary" id="btnSearch" type="button">
                                Search
                            </button>
                        </div>
                    </div>
                </div>
                <!-- Result Filter -->
                <div class="d-flex flex-column gap-4 px-4 mb-4">
                    <div class="filter-summary">
                        <button id="btnDownload" class="btn btn-outline-base btn-download">
                            <span class="icon-download"></span>
                            Download Data
                        </button>
                        <span id="badge-date-report" class="badge bg-filter-value">
                            Tanggal <?= date("d/m/Y"); ?>
                        </span>
                        <span id="badge-search-report" class="badge bg-filter-value" style="display: none"></span>
                        <span id="badge-itp-report" class="badge bg-filter-value" style="display: none"></span>
                        <span id="badge-service-report" class="badge bg-filter-value">Semua Layanan</span>
                        <button id="btn-report-reset" class="btn btn-light btn-reset">Reset Data</button>
                    </div>
                </div>
                <!-- Table -->
                <div class="table-responsive">
                    <table id="itpnow" class="table nowrap mb-0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Mitra Acquirer</th>
                                <th>Layanan</th>
                                <th>Lembar</th>
                                <th>Tagihan (Rp)</th>
                                <th>Admin Mitra Acquirer (Rp)</th>
                                <th>Total (Rp)</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>