<div class="d-flex">
    <img src="<?= $this->baseUrl('/assets/img/logo-mis-black.svg'); ?>" class="d-flex d-md-none img-fluid w-100"
        alt="logo jatelindo">
</div>
<form id="forgot-password-form" class="form form-validation" action="<?= $this->baseUrl('auth/send-otp'); ?>"
    autocomplete="off">
    <a href="/auth/login" class="text-neutral-70 fw-medium">
        <div class="d-flex align-items-center gap-2">
            <img src="<?= $this->baseUrl('assets/img/ic-arrow-back.svg'); ?>" alt="back">
            Kembali
        </div>
    </a>
    <div class="form-header">
        <h1 class="form-header-title">Lupa Kata Sandi</h1>
        <p class="form-header-description">
            Masukkan email terdaftar Anda, dan kami akan mengirimkan kode OTP untuk membuat kata sandi baru Anda.
        </p>
    </div>
    <div class="form-content">
        <div class="form-group">
            <label for="email" class="form-label">Email</label>
            <input id="email" type="email" name="email" class="form-control" v-model="email"
                placeholder="Masukkan email" required />
            <div class="form-feedback"></div>
        </div>
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary btn-full w-full">
            Kirim Kode OTP
        </button>
    </div>
</form>
<!-- OTP Modal -->
<div class="modal fade" id="otpModal" tabindex="-1" aria-labelledby="otpModalLabel" aria-hidden="true"
    data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="otpModalLabel">Kode OTP</h5>
            </div>
            <div class="modal-body">
                <p class="text-sm mb-4">
                    Silakan masukkan OTP 6 digit yang dikirimkan ke
                    <span class="text-dark-70 font-bold" id="otpEmailTarget"></span>
                </p>
                <div class="form-otp">
                    <div class="otp-input-group">
                        <input type="text" name="otpCode[]" maxlength="1" />
                        <input type="text" name="otpCode[]" maxlength="1" />
                        <input type="text" name="otpCode[]" maxlength="1" />
                        <input type="text" name="otpCode[]" maxlength="1" />
                        <input type="text" name="otpCode[]" maxlength="1" />
                        <input type="text" name="otpCode[]" maxlength="1" />
                        <span class="otp-loader"></span>
                    </div>
                    <p class="d-none otp-error-message"></p>
                </div>
            </div>
            <div class="modal-footer justify-content-start border-top-0">
                <p class="text-dark-70 text-sm">
                    Kirim Ulang Kode 1/3
                    <span class="text-dark-70 font-bold timer-otp">02:59</span>
                </p>
            </div>
        </div>
    </div>
</div>

<p class="auth-tos">
</p>

<script type="text/javascript">
$(document).ready(function() {
    app.FormValidation.init("#forgot-password-form");

    let timerInterval = null;

    $('#forgot-password-form').on('submit', function(e) {
        e.preventDefault();
        const form = $(this);

        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            dataType: 'JSON',
            data: form.serialize(),
            beforeSend: function() {
                form.find('button')
                    .prop('disabled', true);
            },
            success: function(response) {
                if (response.success) {
                    $('#otpEmailTarget').text($('#email').val());
                    $('#otpModal').modal('show');
                    setTimeout(() => {
                        $(".otp-input-group").find("input").first().focus();
                    }, 500);
                    startOtpTimer();
                } else {
                    app.FormValidation.feedback('#email', response.message);
                }
            },
            error: function(xhr, status, error) {
                app.FormValidation.feedback('#email',
                    'Failed to send OTP. Please try again.');
            },
            complete: function() {
                form.find('button')
                    .prop('disabled', false);
            }
        });
    });

    const OtpCallback = (value) => {
        inputOtp.isError(false);
        inputOtp.showLoading();

        $.ajax({
            url: "<?= $this->baseUrl('auth/verify-otp-process'); ?>",
            type: "POST",
            dataType: "JSON",
            data: {
                email: $('#email').val(),
                otp: value
            },
            success: function(response) {
                inputOtp.hideLoading();

                if (response.success) {
                    window.location.href = response.redirect;
                } else {
                    $('.otp-error-message').text(response.message);
                    $('.otp-error-message').removeClass('d-none');
                }
            },
            error: function() {
                inputOtp.hideLoading();
                inputOtp.isError(true);
            }
        });
    };

    const inputOtp = app.InputOtp.init(
        OtpCallback
    );

    $(document).on('click', '#resendOtp', function(e) {
        e.preventDefault();

        $.ajax({
            url: "<?= $this->baseUrl('auth/send-otp'); ?>",
            type: "POST",
            dataType: "JSON",
            data: {
                email: $('#email').val()
            },
            success: function(response) {
                if (!response.success) {
                    $('.otp-error-message').text(response.message);
                    $('.otp-error-message').removeClass('d-none');
                    return;
                }

                $('.otp-error-message').addClass('d-none');
                startOtpTimer();
            },
            error: function() {
                $('.otp-error-message').text('Failed to resend OTP.');
                $('.otp-error-message').removeClass('d-none');
            }
        });
    });

    function startOtpTimer() {
        if (timerInterval) {
            clearInterval(timerInterval);
        }

        let duration = 180;

        $('.timer-otp').html('03:00');

        timerInterval = setInterval(function() {
            let minutes = Math.floor(duration / 60);
            let seconds = duration % 60;

            minutes = minutes < 10 ? '0' + minutes : minutes;
            seconds = seconds < 10 ? '0' + seconds : seconds;

            $('.timer-otp').text(minutes + ':' + seconds);

            duration--;

            if (duration < 0) {
                clearInterval(timerInterval);

                $('.timer-otp').html(
                    '<a href="#" id="resendOtp">Resend OTP</a>'
                );
            }
        }, 1000);
    }
});
</script>