<div class="d-flex">
    <img src="<?= $this->baseUrl('/assets/img/logo-mis-black.svg'); ?>" class="d-flex d-md-none img-fluid w-100"
        alt="logo jatelindo">
</div>
<form id="login-form" class="form form-validation" method="POST" action="/auth/login" autocomplete="off">
    <div class="form-header">
        <h1 class="form-header-title">Masuk ke Dashboard</h1>
        <p class="form-header-description">
            Masuk dengan akun Anda
        </p>
    </div>
    <div class="form-content">
        <div class="form-group">
            <label for="email" class="form-label">Email</label>
            <input id="email" type="email" name="email" class="form-control" placeholder="Masukkan email"
                value="<?= $this->escape($this->email); ?>" required />
            <div class="form-feedback"></div>
        </div>
        <div class="form-group">
            <div class="d-flex align-items-center justify-content-between">
                <label for="password" class="form-label">Kata Sandi</label>
                <a href="/auth/forgot-password" class="form-label font-medium text-danger">
                    Lupa Kata Sandi
                </a>
            </div>
            <div class="input-append append-right">
                <input id="password" name="password" class="form-control" type="password"
                    placeholder="Masukkan kata sandi" required />
                <div class="append-icon icon-password" data-toggle="password"></div>
            </div>
            <div class="form-feedback"></div>
        </div>
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary btn-full w-full" name="submit" value="signin" disabled>
            Masuk
        </button>
    </div>
</form>

<div id="modalRedirect" class="modal fade" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
    data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body pb-0">
                <div class="d-flex flex-column align-items-center py-4 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-reset-new-password.svg'); ?>"
                        alt="image new password" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Perbarui Kata Sandi
                        </h3>
                        <p class="text-neutral-70 text-sm text-center px-2">
                            Akun pertama kali digunakan, silakan melakukan perubahan kata sandi dengan yang baru
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <a href="<?= $this->baseUrl('/auth/reset-password'); ?>" class="btn btn-primary flex-fill">
                    Perbarui Kata Sandi
                </a>
            </div>
        </div>
    </div>
</div>

<div id="modalErrorAccount" class="modal fade" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
    data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body pb-0">
                <div class="d-flex flex-column align-items-center py-4 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-account-not-found.svg'); ?>"
                        alt="image account not found" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Akun Tidak Ditemukan
                        </h3>
                        <p class="text-neutral-70 text-sm text-center px-2">
                            Email belum terdaftar, Silahkan lakukan pendaftaran terlebih dahulu.
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary flex-fill" data-bs-dismiss="modal">
                    Tutup
                </button>
            </div>
        </div>
    </div>
</div>

<div id="modalErrorBlocked" class="modal fade" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
    data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body pb-0">
                <div class="d-flex flex-column align-items-center py-4 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-account-not-found.svg'); ?>"
                        alt="image account blocked" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Akun Terblokir
                        </h3>
                        <p class="text-neutral-70 text-sm text-center px-2">
                            Silakan hubungi kami untuk melakukan reset kata sandi
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary flex-fill" data-bs-dismiss="modal">
                    Oke
                </button>
            </div>
        </div>
    </div>
</div>

<p class="auth-tos"></p>

<script type="text/javascript">
$(document).ready(function() {
    app.FormValidation.init("#login-form");

    <?php if ($this->isNewUser) : ?>
    $('#modalRedirect').modal('show');
    <?php endif; ?>

    <?php if ($this->error) : ?>
    app.FormValidation.feedback('#password', "<?= $this->error; ?>");
    <?php endif; ?>

    <?php if ($this->errorPassword) : ?>
    app.FormValidation.feedback('#password', "<?= $this->errorPassword; ?>");
    <?php endif; ?>

    <?php if($this->errorAccount) : ?>
    $('#modalErrorAccount').modal('show');
    <?php endif; ?>

    <?php if($this->errorBlocked) : ?>
    $('#modalErrorBlocked').modal('show');
    <?php endif; ?>
});
</script>