<div class="d-flex">
    <img src="<?= $this->baseUrl('/assets/img/logo-mis-black.svg'); ?>" class="d-flex d-md-none img-fluid w-100"
        alt="logo jatelindo">
</div>
<form id="reset-password-form" class="form form-validation" action="<?= $this->baseUrl('auth/reset-password'); ?>"
    autocomplete="off">
    <a href="/" class="btn btn-link text-neutral-70 fw-medium p-0 text-decoration-none">
        <div class="d-flex align-items-center gap-2">
            <img src="<?= $this->baseUrl('assets/img/ic-arrow-back.svg'); ?>" alt="back">
            Kembali
        </div>
    </a>
    <div class="form-header">
        <h1 class="form-header-title">Perbarui Kata Sandi</h1>
        <p class="form-header-description">
            Buat kata sandi baru
        </p>
    </div>
    <div class="form-content">
        <div class="form-group">
            <label for="newPassword" class="form-label">Kata Sandi Baru</label>
            <div class="input-append append-right">
                <input id="newPassword" name="newPassword" class="form-control password-validate" type="password"
                    minlength="8" placeholder="Masukkan Kata Sandi" required />
                <div class="append-icon icon-password" data-toggle="password"></div>
            </div>
            <div class="term-password mt-2" style="display: none;">
                <div class="d-flex align-items-center gap-2" data-rule="length">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Minimal 8 Karakter</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="upper">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Harus menyertakan huruf besar dan huruf kecil.</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="lower">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Harus menyertakan setidaknya satu karakter khusus.</span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="confirmPassword" class="form-label">Konfirmasi Kata Sandi Baru</label>
            <div class="input-append append-right">
                <input id="confirmPassword" name="confirmPassword" class="form-control password-validate"
                    type="password" minlength="8" placeholder="Masukkan Kata Sandi Baru" required />
                <div class="append-icon icon-password" data-toggle="password"></div>
            </div>
            <div class="term-password mt-2" style="display: none;">
                <div class="d-flex align-items-center gap-2" data-rule="length">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Minimal 8 Karakter</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="upper">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Harus menyertakan huruf besar dan huruf kecil.</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="lower">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Harus menyertakan setidaknya satu karakter khusus.</span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary btn-full w-full">
            Save New Password
        </button>
    </div>
</form>
<p class="auth-tos">
</p>
<div id="modalSuccess" class="modal fade" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
    data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body pb-0">
                <div class="d-flex flex-column align-items-center py-4 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-new-password.svg'); ?>" alt="image new password" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Kata Sandi Berhasil Diperbarui
                        </h3>
                        <p class="text-neutral-70 text-sm text-center px-4">
                            Jaga kerahasiaan kata sandi Anda untuk memastikan keamanan akun Anda
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <a href="<?= $this->baseUrl('/auth/login'); ?>" class="btn btn-primary flex-fill">
                    Masuk Kembali
                </a>
            </div>
        </div>
    </div>
</div>
<div id="modalFailed" class="modal fade" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
    data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="d-flex flex-column align-items-center py-4 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-failed-new-password.svg'); ?>"
                        alt="image new password" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Kata Sandi Gagal Diperbarui
                        </h3>
                        <p class="text-neutral-70 text-sm text-center">
                            Gagal mengubah kata sandi. Silakan coba lagi.
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger flex-fill" data-bs-dismiss="modal">
                    Kembali
                </button>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    app.FormValidation.init("#reset-password-form");
    app.ValidatePassword.init('.password-validate');

    $('.form').on('submit', function(e) {
        e.preventDefault();
        const form = $(this);

        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            dataType: 'JSON',
            data: form.serialize(),
            beforeSend: function() {
                form.find('button')
                    .prop('disabled', true);
            },
            success: function(response) {
                if (response.success) {
                    $('#modalSuccess').modal('show');
                } else {
                    $('#modalFailed').modal('show');
                }
            },
            error: function() {
                $('#modalFailed').modal('show');
            },
            complete: function() {
                form.find('button')
                    .prop('disabled', false);
            }
        });
    });
});
</script>