<div class="d-flex">
    <img src="<?= $this->baseUrl('assets/img/logo-jatelindo-black.svg'); ?>" class="d-flex d-md-none img-fluid w-100"
        alt="logo jatelindo">
</div>
<form id="reset-password-form" class="form form-validation" action="<?= $this->baseUrl('auth/reset-password'); ?>"
    autocomplete="off">
    <button type="button" class="btn btn-link text-neutral-70 fw-medium p-0 text-decoration-none"
        @click="openLeaveModal">
        <div class="d-flex align-items-center gap-2">
            <img src="<?= $this->baseUrl('assets/img/ic-arrow-back.svg'); ?>" alt="back">
            Back
        </div>
    </button>
    <div class="form-header">
        <h1 class="form-header-title">Reset Password</h1>
        <p class="form-header-description">
            Create your new password
        </p>
    </div>
    <div class="form-content">
        <div class="form-group">
            <label for="newPassword" class="form-label">New Password</label>
            <div class="input-append append-right">
                <input id="newPassword" name="newPassword" class="form-control password-validate" type="password"
                    minlength="8" placeholder="Enter new password" required />
                <div class="append-icon icon-password" data-toggle="password"></div>
            </div>
            <div class="term-password mt-2" style="display: none;">
                <div class="d-flex align-items-center gap-2" data-rule="length">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Minimum of 8 characters</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="upper">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Must include uppercase letters (A-Z)</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="lower">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Must include lowercase letters (a-z)</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="special">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Must include at least one special character</span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="confirmPassword" class="form-label">Confirm New Password</label>
            <div class="input-append append-right">
                <input id="confirmPassword" name="confirmPassword" class="form-control password-validate"
                    type="password" minlength="8" placeholder="Enter new password" required />
                <div class="append-icon icon-password" data-toggle="password"></div>
            </div>
            <div class="term-password mt-2" style="display: none;">
                <div class="d-flex align-items-center gap-2" data-rule="length">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Minimum of 8 characters</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="upper">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Must include uppercase letters (A-Z)</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="lower">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Must include lowercase letters (a-z)</span>
                </div>
                <div class="d-flex align-items-center gap-2" data-rule="special">
                    <span class="ic icon-checklist"></span>
                    <span class="term-item">Must include at least one special character</span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary btn-full w-full">
            Save New Password
        </button>
    </div>
</form>
<p class="auth-tos">
</p>
<div id="modalSuccess" class="modal fade" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
    data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="d-flex flex-column align-items-center py-4 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-new-password.svg'); ?>" alt="image new password" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Password Updated
                        </h3>
                        <p class="text-neutral-70 text-sm text-center">
                            Keep your password private to ensure your account's security
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <a href="<?= $this->baseUrl('/auth/login'); ?>" class="btn btn-primary flex-fill">
                    Login Again
                </a>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    app.FormValidation.init("#reset-password-form");
    app.ValidatePassword.init('.password-validate');

    $('.form').on('submit', function(e) {
        e.preventDefault();
        const form = $(this);

        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            dataType: 'JSON',
            data: form.serialize(),
            beforeSend: function() {
                form.find('button')
                    .prop('disabled', true);
            },
            success: function(response) {
                if (response.success) {
                    $('#modalSuccess').modal('show');
                } else {
                    app.Toast.fire({
                        icon: "error",
                        iconHtml: '<img src="<?= $this->baseUrl('/assets/img/ic-toast-error.svg'); ?>" />',
                        text: response.message,
                        timer: 3000,
                        timerProgressBar: true,
                        customClass: {
                            container: "swal2-custom",
                        },
                    });
                }
            },
            error: function() {
                app.Toast.fire({
                    icon: "error",
                    iconHtml: '<img src="<?= $this->baseUrl('/assets/img/ic-toast-error.svg'); ?>" />',
                    text: "Internal Server Error",
                    timer: 3000,
                    timerProgressBar: true,
                    customClass: {
                        container: "swal2-custom",
                    },
                });
            },
            complete: function() {
                form.find('button')
                    .prop('disabled', false);
            }
        });
    });
});
</script>