<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <?= $this->headTitle('ASP Portal Biller')->setSeparator(' - '); ?>
    <meta name="theme-color" content="#0092D5">
    <link rel="icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-32x32.webp'); ?>" sizes="32x32" />
    <link rel="icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-192x192.webp'); ?>"
        sizes="192x192" />
    <link rel="apple-touch-icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-180x180.webp'); ?>" />
    <link rel="shortcut icon" href="<?= $this->baseUrl('/assets/img/'); ?>icon-launcher.png" />
    <link rel="stylesheet" href="<?= $this->baseUrl('/assets/css/fonts.css'); ?>" />
    <link rel="stylesheet" href="<?= $this->baseUrl('/assets/css/app.min.css'); ?>" />
    <style>
    body {
        font-family: "Sora", sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
        -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }

    .container {
        text-align: center;
        max-width: 500px;
        padding: 20px;
    }

    .image-container {
        margin-bottom: 24px;
        display: flex;
        justify-content: center;
    }

    .error-svg {
        width: 100%;
        max-width: 320px;
        height: auto;
    }

    h1 {
        font-size: 20px;
        margin-top: 0;
        /* Tambahkan ini agar jarak ke gambar tetap murni 24px */
        margin-bottom: 8px;
        color: #12161C;
        font-weight: 600;
    }

    p {
        font-size: 16px;
        color: #595C60;
        margin-top: 0;
        /* Tambahkan ini agar jarak dari H1 ke P tetap murni 8px */
        margin-bottom: 60px;
        line-height: 1.6;
    }

    .btn-go-back {
        background-color: #3A7BF6;
        color: white;
        padding: 12px 40px;
        font-size: 14px;
        font-weight: 600;
        border-radius: 8px;
        text-decoration: none;
        display: inline-block;
        transition: 0.3s ease;
    }

    .btn-go-back:hover {
        background-color: #3A7BF6;
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(83, 131, 236, 0.3);
    }
    </style>
</head>

<body>
    <div class="container">
        <?=$this->layout()->content; ?>
    </div>
</body>

</html>