<div class="image-container">
    <img src="<?= $this->baseUrl('assets/img/img_error_message_500.svg'); ?>" alt="Error Illustration"
        class="error-svg" />
</div>

<h1>Unexpected error</h1>
<p>An unexpected error has occurred</p>

<a href="#" class="btn-go-back" onclick="history.go(-1)">Go Back</a>

<pre class="w-100">
<?php echo $this->exception->getMessage(); ?>
<?php echo $this->exception->getTraceAsString(); ?>
</pre>