<p style="margin-top: 16px;">
    Terima kasih,<br>
    <strong>MIS Portal Biller</strong>
</p>

<hr />

<p style="font-size: 13px; color: #555555; margin-bottom: 0">
    Apabila membutuhkan bantuan atau informasi lebih lanjut, silakan
    hubungi kami melalui kontak berikut ini:<br />
    <strong>Email :</strong> helpdesk@jatelindo.co.id<br />
    <strong>Phone :</strong> +628118822249
</p>
</td>
</tr>
</table>
<div class="footer">
    PT Jatelindo Perkasa Abadi<br />
    Jalan Sunan Kalijaga Blok K5 No.63B, Melawai, Kebayoran Baru, Jakarta
    Selatan 12160
</div>