<div class="header">
    <table width="100%" border="0" cellpadding="0" cellspacing="0" class="header-table">
        <tr>
            <td class="header-title" style="
                font-size: 28px;
                font-weight: bold;
                color: #ffffff;
                vertical-align: middle;
            ">
                MIS Portal Biller
            </td>
            <td class="header-logo" align="right" style="vertical-align: middle">
                <img src="<?= $this->logo; ?>" alt="Logo Jatelindo" style="display: block; height: 35px; width: auto" />
            </td>
        </tr>
    </table>
</div>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td class="content-cell">