<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <?= $this->headTitle('Portal MIS')->setSeparator(' - '); ?>
    <meta name="theme-color" content="#0092D5">
    <link rel="icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-32x32.webp'); ?>" sizes="32x32" />
    <link rel="icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-192x192.webp'); ?>"
        sizes="192x192" />
    <link rel="apple-touch-icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-180x180.webp'); ?>" />
    <link rel="shortcut icon" href="<?= $this->baseUrl('/assets/img/'); ?>icon-launcher.png" />
    <link rel="stylesheet" href="<?= $this->baseUrl('/assets/css/fonts.css'); ?>" />
    <link rel="stylesheet" href="<?= $this->baseUrl('/assets/css/app.min.css'); ?>" />
    <script src="<?= $this->baseUrl('/assets/js/app.min.js'); ?>"></script>
</head>

<body>
    <div class="modal fade" id="modalLoading" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="modalLoadingLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-fit">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="d-flex flex-column align-items-center gap-2">
                        <span class="spinner-progress"></span>
                        <h3 id="modalLoadingTitle" class="text-neutral-100 fs-7 fw-bold mb-0">
                            Loading
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main">
        <div class="auth-side-cover">
            <div class="d-flex align-items-start">
                <img src="<?= $this->baseUrl('assets/img/logo-mis.png'); ?>" class="img-fluid" />
            </div>
        </div>
        <div class="auth-side-form">
            <?=$this->layout()->content; ?>
        </div>
    </div>
</body>

</html>