<div class="content-header">
    <h1 class="header-title">Profile</h1>
</div>
<div class="content-body">
    <div class="card card-profile">
        <div class="card-header profile-header">
            <div class="d-flex gap-3">
                <span class="profile-initial"><?= $this->initialUser; ?></span>
                <div class="d-flex flex-column flex-fill">
                    <h1 class="profile-name"><?= $this->user['fullName']; ?></h1>
                    <span class="profile-role">
                        <?= $this->user['role']; ?>
                    </span>
                </div>
                <span class="badge badge-profile profile-active">Aktif</span>
            </div>
        </div>
        <div class="card-body">
            <div class="d-flex flex-column gap-4">
                <div class="card card-accordion shadow-none" id="accountInformation">
                    <div class="card-header" data-bs-toggle="collapse" data-bs-target="#collapseInformation"
                        aria-expanded="true" aria-controls="collapseInformation">
                        <div class="card-title">
                            <div class="d-flex flex-column">
                                <h1 class="fs-6 font-bold mb-0">Informasi Akun</h1>
                            </div>
                        </div>
                    </div>
                    <div id="collapseInformation" class="accordion-collapse collapse show"
                        data-bs-parent="#accountInformation">
                        <div class="accordion-body">
                            <div class="d-flex flex-column p-4 py-0 border-top">
                                <div class="d-flex flex-column gap-4">
                                    <div class="d-flex flex-column">
                                        <div
                                            class="d-flex align-items-center justify-content-between py-3 border-bottom">
                                            <span class="fs-7 text-neutral-70">User ID</span>
                                            <span class="fs-7 text-neutral-100">
                                                <?= $this->user['id']; ?>
                                            </span>
                                        </div>
                                        <div
                                            class="d-flex align-items-center justify-content-between py-3 border-bottom">
                                            <span class="fs-7 text-neutral-70">Nama</span>
                                            <span class="fs-7 text-neutral-100">
                                                <?= $this->user['fullName']; ?>
                                            </span>
                                        </div>
                                        <div
                                            class="d-flex align-items-center justify-content-between py-3 border-bottom">
                                            <span class="fs-7 text-neutral-70">Email</span>
                                            <span class="fs-7 text-neutral-100">
                                                <?= $this->user['email']; ?>
                                            </span>
                                        </div>
                                        <div
                                            class="d-flex align-items-center justify-content-between py-3 border-bottom">
                                            <span class="fs-7 text-neutral-70">Level User</span>
                                            <span class="fs-7 text-neutral-100">
                                                <?= $this->user['level']; ?>
                                            </span>
                                        </div>
                                        <div
                                            class="d-flex align-items-center justify-content-between py-3 border-bottom">
                                            <span class="fs-7 text-neutral-70">Role</span>
                                            <span class="fs-7 text-neutral-100">
                                                <?= $this->user['role']; ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card card-accordion shadow-none" id="cardChangePassword">
                    <div id="collapseChangePassword" class="accordion-collapse collapse show"
                        data-bs-parent="#cardChangePassword">
                        <div class="accordion-body">
                            <div class="d-flex align-items-center justify-content-between p-4">
                                <p class="form-label fs-6 text-neutral-100 fw-bold mb-0">
                                    Pengaturan
                                </p>
                                <button class="btn btn-outline-warning bg-hover-warning-subtle" data-bs-toggle="modal"
                                    data-bs-target="#modalChangePassword">
                                    <div class="d-flex align-items-center gap-1">
                                        <span class="icon-lock"></span>
                                        Ubah Kata Sandi
                                    </div>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalChangePassword" data-bs-backdrop="static" data-bs-keyboard="false"
    data-bs-focus="false" tabindex="-1" aria-labelledby="modalChangePasswordLabel">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ubah Kata Sandi</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" tabindex="-1" data-bs-focus="false"
                    aria-label="Close"></button>
            </div>
            <form id="change-password-form" class="form form-validation d-block" action="" method="POST"
                autocomplete="off">
                <div class="modal-body">
                    <div class="form-content">
                        <div class="form-group">
                            <label for="currentPassword" class="form-label">Kata Sandi Saat Ini <span class="merahSandi">*</span></label>
                            <div class="input-append append-right">
                                <input id="currentPassword" name="currentPassword" class="form-control" type="password"
                                    minlength="8" placeholder="Enter current password" required />
                                <div class="append-icon icon-password" data-toggle="password"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="newPassword" class="form-label">Kata Sandi Baru <span class="merahSandi">*</span></label>
                            <div class="input-append append-right">
                                <input id="newPassword" name="newPassword" class="form-control password-validate"
                                    type="password" minlength="8" placeholder="Enter new password" required />
                                <div class="append-icon icon-password" data-toggle="password"></div>
                            </div>
                            <div class="term-password mt-2" style="display: none;">
                                <div class="d-flex align-items-center gap-2" data-rule="length">
                                    <span class="ic icon-checklist"></span>
                                    <span class="term-item">Minimal 8 Karakter</span>
                                </div>
                                <div class="d-flex align-items-center gap-2" data-rule="upper">
                                    <span class="ic icon-checklist"></span>
                                    <span class="term-item">Harus menyertakan huruf besar dan huruf kecil.</span>
                                </div>
                                <div class="d-flex align-items-center gap-2" data-rule="special">
                                    <span class="ic icon-checklist"></span>
                                    <span class="term-item">Harus menyertakan setidaknya satu karakter khusus.</span>
                                </div>
                            </div>
                            <div class="term-password-err mt-2" style="display: none;" id="term-password-2">
                                <div class="d-flex align-items-center gap-2" data-rule="length">
                                    <span class="ic icon-checklist-invalid"></span>
                                    <span class="term-item">Kata Sandi baru tidak boleh sama dengan Kata Sandi lama</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="confirmPassword" class="form-label">Konfirmasi Kata Sandi Baru <span class="merahSandi">*</span></label>
                            <div class="input-append append-right">
                                <input id="confirmPassword" name="confirmPassword"
                                    class="form-control password-validate" type="password" minlength="8"
                                    placeholder="Enter new password" required />
                                <div class="append-icon icon-password" data-toggle="password"></div>
                            </div>
                            <div class="term-password mt-2" style="display: none;">
                                <div class="d-flex align-items-center gap-2" data-rule="length">
                                    <span class="ic icon-checklist"></span>
                                    <span class="term-item">Minimal 8 Karakter</span>
                                </div>
                                <div class="d-flex align-items-center gap-2" data-rule="upper">
                                    <span class="ic icon-checklist"></span>
                                    <span class="term-item">Must include uppercase letters (A-Z)</span>
                                </div>
                                <div class="d-flex align-items-center gap-2" data-rule="special">
                                    <span class="ic icon-checklist"></span>
                                    <span class="term-item">Harus menyertakan setidaknya satu karakter khusus.</span>
                                </div>
                            </div>
                            <div class="term-password-err mt-2" style="display: none;" id="term-password-3"> 
                                <div class="d-flex align-items-center gap-2" data-rule="length">
                                    <span class="ic icon-checklist-invalid"></span>
                                    <span class="term-item">Kata Sandi tidak sama dengan Kata Sandi Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input id="sess" name="sess" class="form-control password-validate" type="hidden" value="<?= $this->user['session_token']; ?>"/>
                    <input id="email" name="email" class="form-control password-validate" type="hidden" value="<?= $this->user['email']; ?>"/>
                    <input id="ip" name="ip" class="form-control password-validate" type="hidden" value="<?= App_Log_Context::getIp(); ?>"/>
                    <input id="useragent" name="useragent" class="form-control password-validate" type="hidden" value="<?= App_Log_Context::getUserAgent(); ?>"/>
                    <button type="button" class="btn btn-primary w-100" id="ChngPass">
                        Perbarui Kata Sandi
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="loadingScreen">
    <div class="loading-box">

        <div class="spinner"></div>

        <div class="loading-text">
            Loading
        </div>

    </div>
</div>


<div id="modalSuccess" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="d-flex flex-column align-items-center pt-2 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-new-password.svg'); ?>" alt="image new password" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Kata Sandi Berhasil Diperbarui 
                        </h3>
                        <p class="text-neutral-70 text-sm text-center">
                            Demi keamanan, silakan masuk kembali menggunakan kata sandi yang baru
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary flex-fill" data-bs-dismiss="modal"
                    data-bs-target="#modalSuccess" id="btnModalSuccessok">Masuk Kembali</button>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="errorModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="d-flex flex-column align-items-center pt-2 gap-4">
                    <img src="<?= $this->baseUrl('assets/img/img-new-password.svg'); ?>" alt="image new password" />
                    <div class="d-flex flex-column align-items-center gap-2">
                        <h3 class="text-neutral-100 fs-5 fw-bold mb-0">
                            Kata Sandi Gagal Diperbarui
                        </h3>
                        <p class="text-neutral-70 text-sm text-center text-response">
               
                        </p>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary flex-fill" data-bs-dismiss="modal"
                    data-bs-target="#errorModal" id="btnModalErrorok">Ok</button>
            </div>
        </div>
    </div>
</div>



