
<div class="container-fluid px-2 pb-4 pt-3 bg-light min-vh-100 text-dark">

    <h3 class="fw-bold mb-4 c-24">Log Aktivitas</h3>

    <div class="card card-dashboard">

        <div class="card-body">

            <h5 class="fw-bold mb-4 c-16">
                List Data
            </h5>



            <!-- Filter -->

            <div class="row g-3 mb-3 mt-1">
                <form method="POST" action="" class="d-flex align-items-center gap-3 w-100 m-0">

                    <div class="col-md-1">
                        <select class="form-select c-14">
                            <option>10</option>
                        </select>
                    </div>

                    <div class="col cariinputcustoms c-14">

                        <div class="position-relative">

                            <span class="search-icon">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
                                    <circle cx="11" cy="11" r="7" stroke="#9CA3AF" stroke-width="2"/>
                                    <path d="M20 20L17 17" stroke="#9CA3AF" stroke-width="2" stroke-linecap="round"/>
                                </svg>
                            </span>

                            <input type="text"
                                   class="form-control search-input"
                                   placeholder="Cari" id="keyword">

                        </div>

                    </div>

                    <div class="col-md-2 calendar-input-container">
                        <input type="date" class="custom-date-input-with-icon empty-date-logic" value="<?=date('Y-m-d'); ?>" data-placeholder="Pilih tanggal" required>
                    </div>

                    <div class="col-md-2 c-14">
                        <select class="form-select select2" id="leveluser" style="width:auto !important;">
                            <option value=""></option>
                            <?php foreach($this->listDatalevel as $key => $value){ ?>

                                <option value="<?php echo $value['id']; ?>">
                                    <?php echo $value['level_name']; ?>
                                </option>

                            <?php } ?>

                        </select>
                    </div>

                    <div class="col-md-2 c-14">
                        <select class="form-select select2" id="roleuser" style="width:auto !important;">
                            <option value=""></option>
                            <?php foreach($this->listDataRoles as $key => $value){ ?>

                                <option value="<?php echo $value['id']; ?>">
                                    <?php echo $value['role_name']; ?>
                                </option>

                            <?php } ?>

                        </select>
                    </div>

                    <div class="col-auto ms-auto c-14">
                        <button class="btn btn-outline-primary" id="btnSearchActivity" type="button">
                            Search
                        </button>
                    </div>
                </form>
            </div>

            <!-- Button -->

            <div class="d-flex gap-3 mb-3">

                 <div id="badge-date-report" class="rounded-3 d-flex align-items-center justify-content-center px-3" style="height: 36px; background: #EBF2FE; color: #12161C; font-size: 14px; font-weight: 600;">
                        Tanggal <?=date("d/m/Y");?>
                </div>

                <div id="badge-level-activity" class="rounded-3 d-flex align-items-center justify-content-center px-3" style="height: 36px; background: #EBF2FE; color: #12161C; font-size: 14px; font-weight: 600; display: none !important;">
                          
                </div>

                <div id="badge-role-activity" class="rounded-3 d-flex align-items-center justify-content-center px-3" style="height: 36px; background: #EBF2FE; color: #12161C; font-size: 14px; font-weight: 600; display: none !important;">
                          
                </div>

                <button class="btn btn-link text-dark c-14" id="btn-report-reset" style="color: #595C60; font-size: 14px;text-decoration: none;">
                    Reset Data
                </button>

            </div>

            <!-- Table -->

            <div class="table-container" >

                <table class="table table-hover align-middle w-100" id="activitynow">

                    <thead>

                    <tr>

                        <th>No</th>
                        <th>Tanggal&Waktu</th>
                        <th>Nama User</th>
                        <th>Level User</th>
                        <th>Role</th>
                        <th>Aktifitas</th>
                        <th>Browser</th>
                        <th>Deskripsi</th>

                    </tr>

                    </thead>

                    <tbody>


                    </tbody>

                </table>

            </div>

        </div>

    </div>

</div>

