<h2>Halo, <strong>Maker</strong></h2>

<p>Disbursement telah diperbarui oleh Maker <strong><?= $this->updatedBy; ?></strong>.<br>
    Silakan melakukan review dan persetujuan melalui portal mis.</p>

<table class="info-table">
    <tr>
        <td class="label">ID Disbursement</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->disbursementId; ?></td>
    </tr>
    <tr>
        <td class="label">Nama Disbursement</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->disbursementTitle; ?></td>
    </tr>
    <tr>
        <td class="label">Tipe Transaksi</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->disbursementType; ?></td>
    </tr>
    <tr>
        <td class="label">Tanggal Disbursement</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->disbursementDate; ?></td>
    </tr>
</table>

<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="padding-top: 24px; text-align: left;">
            <a href="<?= $this->url; ?>" class="btn-click" style="color: #fff">Login ke Web</a>
        </td>
    </tr>
</table>