<h2>Halo, <strong><?= $this->misName; ?></strong></h2>

<p>Kata sandi akun MIS Portal Biller telah berhasil direset, silakan masuk menggunakan kata sandi baru yang telah direset.
</p>

<table class="info-table">
    <tr>
        <td class="label">ID Akun</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->misId; ?></td>
    </tr>
    <tr>
        <td class="label">Nama Akun</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->misName; ?></td>
    </tr>
    <tr>
        <td class="label">Email</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->misEmail; ?></td>
    </tr>
    <tr>
        <td class="label">Role</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->misRole; ?></td>
    </tr>
    <tr>
        <td class="label">Password</td>
        <td class="colon">:</td>
        <td class="value"><?= $this->misPassword; ?></td>
    </tr>
</table>

<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="padding-top: 24px; text-align: left;">
             <a href="<?= $this->misUrl; ?>" class="btn-click" style="color: #fff">Login ke Web</a>
        </td>
    </tr>
</table>