<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <?= $this->headTitle('Portal MIS')->setSeparator(' - '); ?>
    <meta name="theme-color" content="#0092D5">
    <link rel="icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-32x32.webp'); ?>" sizes="32x32" />
    <link rel="icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-192x192.webp'); ?>"
        sizes="192x192" />
    <link rel="apple-touch-icon" href="<?= $this->baseUrl('/assets/img/cropped-Jatelindo-Warna-180x180.webp'); ?>" />
    <link rel="shortcut icon" href="<?= $this->baseUrl('/assets/img/'); ?>icon-launcher.png" />
    <link rel="stylesheet" href="<?= $this->baseUrl('/assets/css/fonts.css'); ?>" />
    <link rel="stylesheet" href="<?= $this->baseUrl('/assets/css/app.min.css'); ?>" />
    <script src="<?= $this->baseUrl('/assets/js/app.min.js'); ?>"></script>
</head>

<body>
    <div class="main">
        <div class="auth-side-cover">
            <div class="d-flex align-items-start">
                <img src="<?= $this->baseUrl('assets/img/logo-jatelindo.svg'); ?>" class="img-fluid" />
            </div>
            <div class="auth-side-title">
                <h1>Portal <br /> Disbursement</h1>
                <p>Manage all disbursements with a safe, efficient, and transparent process</p>
            </div>
        </div>
        <div class="auth-side-form">
            <?=$this->layout()->content; ?>
        </div>
    </div>
</body>

</html>