[production]
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0

includePaths.library = APPLICATION_PATH "/../library"

bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"

resources.frontController.moduleDirectory = APPLICATION_PATH "/modules"
resources.modules[] =
resources.frontController.params.prefixDefaultModule = "1"
resources.frontController.defaultModule = "default"
resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts"

; api.baseUrl = 'http://182.23.62.7:8299'
api.baseUrl = 'http://192.168.77.154:8085'
api.apiKey = '019d25b4-eca7-7fe9-800c-ec9f9e8ff616'
api.clientSecret = '4710a316724ce332f9c9dc5f8a7060f2'
api.userAuth = 'web_portal_mis'
api.userPassword = '123456'

[development : production]
phpSettings.display_errors = 0
resources.frontController.params.displayExceptions = 0

; api.baseUrl = 'http://182.23.62.7:8299'
api.baseUrl = 'http://192.168.77.154:8085'
api.apiKey = '019d25b4-eca7-7fe9-800c-ec9f9e8ff616'
api.clientSecret = '4710a316724ce332f9c9dc5f8a7060f2'
api.userAuth = 'web_portal_mis'
api.userPassword = '123456'